name: my workflow
on: 
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: show default go version
        run: go version

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.20'     
      
      - name: show current go version
        run: go version 

      - name: test 
        run: |
          make test

